language: java
# Use Ubuntu Percise explicitly to enable using Oracle JDK7
# See: https://github.com/travis-ci/travis-ci/issues/7884
dist: precise
jdk:
  - oraclejdk7
before_install:
  - chmod +x .travis/mvn
  - chmod +x .travis/bintray
  - chmod +x .travis/deploy.sh
install: .travis/mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: .travis/mvn verify
after_success:
  # -- Codacy --
  - .travis/mvn codacy:coverage
deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    tags: true